-- Complete the core category catalog from the shop master list.

WITH catalog(category, subcategory) AS (VALUES
  ('Marble','Brown Marble'),('Marble','Pink Marble'),('Marble','Grey Marble'),('Marble','Makrana Marble'),('Marble','Katni Marble'),('Marble','Morwad Marble'),('Marble','Banswara Marble'),('Marble','Ambaji Marble'),('Marble','Udaipur Marble'),('Marble','Italian Marble'),('Marble','Turkish Marble'),('Marble','Spanish Marble'),('Marble','Vietnam Marble'),
  ('Granite','Brown Granite'),('Granite','Pink Granite'),('Granite','Blue Granite'),('Granite','Galaxy Granite'),('Granite','Steel Grey Granite'),('Granite','Absolute Black'),('Granite','Black Galaxy'),('Granite','Tan Brown'),('Granite','Kashmir White'),('Granite','Colonial White'),('Granite','River White'),
  ('Tiles','Ceramic Floor Tiles'),('Tiles','Vitrified Floor Tiles'),('Tiles','Porcelain Tiles'),('Tiles','Full Body Vitrified Tiles'),('Tiles','Double Charge Tiles'),('Tiles','Glazed Vitrified Tiles'),('Tiles','Matt Finish Tiles'),('Tiles','Glossy Finish Tiles'),('Tiles','Anti-Skid Tiles'),('Tiles','Ceramic Wall Tiles'),('Tiles','Glazed Wall Tiles'),('Tiles','Digital Wall Tiles'),('Tiles','Decorative Wall Tiles'),('Tiles','Subway Tiles'),('Tiles','3D Wall Tiles'),('Tiles','Anti-Skid Bathroom Tiles'),('Tiles','Shower Area Tiles'),('Tiles','Wet Area Tiles'),('Tiles','Kitchen Wall Tiles'),('Tiles','Kitchen Backsplash Tiles'),('Tiles','Kitchen Floor Tiles'),('Tiles','Decorative Kitchen Tiles'),('Tiles','Outdoor Floor Tiles'),('Tiles','Anti-Skid Outdoor Tiles'),('Tiles','Heavy Duty Tiles'),('Tiles','Garden Tiles'),('Tiles','Terrace Tiles'),('Tiles','Exterior Elevation Tiles'),('Tiles','Stone Look Elevation Tiles'),('Tiles','Brick Look Tiles'),('Tiles','3D Elevation Tiles'),('Tiles','Decorative Elevation Tiles'),('Tiles','Heavy Duty Parking Tiles'),('Tiles','Car Parking Tiles'),('Tiles','Driveway Tiles'),('Tiles','Outdoor Parking Tiles'),('Tiles','Marble Look Tiles'),('Tiles','Stone Look Tiles'),('Tiles','Wood Look Tiles'),('Tiles','Metal Look Tiles'),('Tiles','Fabric Look Tiles'),('Tiles','Designer Pattern Tiles'),('Tiles','Large Format Tiles'),('Tiles','Stair Tiles'),('Tiles','Step Tiles'),('Tiles','Skirting Tiles'),('Tiles','Corner Tiles'),('Tiles','Border Tiles'),('Tiles','Mosaic Tiles'),('Tiles','Swimming Pool Tiles'),
  ('Sanitaryware','Close Coupled WC'),('Sanitaryware','Floor Mounted WC'),('Sanitaryware','Back to Wall WC'),('Sanitaryware','Smart Toilet'),('Sanitaryware','Toilet Seat'),('Sanitaryware','Wall Hung Wash Basin'),('Sanitaryware','Under Counter Basin'),('Sanitaryware','Semi Recessed Basin'),('Sanitaryware','Pedestal Basin'),('Sanitaryware','Corner Basin'),('Sanitaryware','Above Counter Basin'),('Sanitaryware','Wall Mounted Urinal'),('Sanitaryware','Automatic Urinal'),('Sanitaryware','Urinal Partition'),('Sanitaryware','Towel Rod'),('Sanitaryware','Towel Ring'),('Sanitaryware','Towel Rack'),('Sanitaryware','Soap Dish'),('Sanitaryware','Soap Dispenser'),('Sanitaryware','Toothbrush Holder'),('Sanitaryware','Toilet Paper Holder'),('Sanitaryware','Robe Hook'),('Sanitaryware','Bathroom Shelf'),('Sanitaryware','Corner Shelf'),('Sanitaryware','Bathroom Set'),('Sanitaryware','Cistern'),('Sanitaryware','Flush Tank'),('Sanitaryware','Toilet Seat Cover'),('Sanitaryware','Health Faucet'),('Sanitaryware','Floor Trap'),('Sanitaryware','Waste Coupling'),('Sanitaryware','Bottle Trap'),('Sanitaryware','Drain Cover'),
  ('Kitchen Sink','Triple Bowl Sink'),('Kitchen Sink','Granite Sink'),('Kitchen Sink','Nano Coated Sink'),('Kitchen Sink','Undermount Sink'),('Kitchen Sink','Top Mount Sink'),('Kitchen Sink','Flush Mount Sink'),('Kitchen Sink','Corner Sink'),('Kitchen Sink','Bar Sink'),('Kitchen Sink','Utility Sink'),
  ('Bathroom Vanity','MDF Vanity'),('Bathroom Vanity','Acrylic Vanity'),('Bathroom Vanity','Waterproof Vanity'),('Bathroom Vanity','Floating Vanity'),('Bathroom Vanity','Double Basin Vanity'),('Bathroom Vanity','Single Basin Vanity'),('Bathroom Vanity','Vanity with Mirror'),('Bathroom Vanity','Vanity with LED Mirror'),('Bathroom Vanity','Vanity with Storage')
)
INSERT INTO subcategories (category_id, name)
SELECT c.id, catalog.subcategory FROM catalog JOIN categories c ON c.name = catalog.category
ON CONFLICT (category_id, name) DO NOTHING;
