-- Expand the catalog for the complete marble, stone, tile, bathroom and installation range.
-- Inventory types: slab, box, piece, mixed (count + area), and job.

ALTER TABLE categories DROP CONSTRAINT IF EXISTS categories_inventory_type_check;
ALTER TABLE categories ADD CONSTRAINT categories_inventory_type_check
  CHECK (inventory_type IN ('slab','box','piece','mixed','job'));

INSERT INTO categories (name, inventory_type, display_order) VALUES
  ('Marble Statue','piece',7),
  ('Marble Home Interior','mixed',8),
  ('Granite Home Interior','mixed',9),
  ('Marble & Granite Custom Work','job',10),
  ('Bathroom Fittings','piece',11),
  ('Bathroom Accessories','piece',12),
  ('Bathtub & Shower','piece',13),
  ('Doors, Windows & Stone Products','mixed',14),
  ('Mosaic & Decorative Products','mixed',15),
  ('Tile Accessories & Installation Material','piece',16),
  ('Plumbing & Bathroom Installation Products','piece',17),
  ('Marble / Granite Chemicals & Maintenance','piece',18),
  ('Hardware & Installation Accessories','piece',19)
ON CONFLICT (name) DO UPDATE SET inventory_type = EXCLUDED.inventory_type, display_order = EXCLUDED.display_order;

WITH catalog(category, subcategory) AS (VALUES
  ('Marble Statue','Marble God Statues'),('Marble Statue','Marble Goddess Statues'),('Marble Statue','Radha Krishna Statue'),('Marble Statue','Lord Krishna Statue'),('Marble Statue','Lord Shiva Statue'),('Marble Statue','Lord Ganesha Statue'),('Marble Statue','Goddess Durga Statue'),('Marble Statue','Goddess Lakshmi Statue'),('Marble Statue','Goddess Saraswati Statue'),('Marble Statue','Hanuman Statue'),('Marble Statue','Ram Darbar Statue'),('Marble Statue','Buddha Statue'),('Marble Statue','Jain Tirthankar Statue'),('Marble Statue','Mahavir Statue'),('Marble Statue','Decorative Marble Statue'),('Marble Statue','Couple Statue'),('Marble Statue','Human Figure Statue'),('Marble Statue','Animal Statue'),('Marble Statue','Elephant Statue'),('Marble Statue','Horse Statue'),('Marble Statue','Lion Statue'),('Marble Statue','Bird Statue'),('Marble Statue','Garden Statue'),('Marble Statue','Fountain Statue'),('Marble Statue','Temple Statue'),('Marble Statue','Custom Marble Statue'),('Marble Statue','Other Marble Statue'),
  ('Marble Home Interior','Marble Flooring'),('Marble Home Interior','Marble Wall Cladding'),('Marble Home Interior','Marble Staircase'),('Marble Home Interior','Marble Steps'),('Marble Home Interior','Marble Kitchen Countertop'),('Marble Home Interior','Marble Kitchen Platform'),('Marble Home Interior','Marble Dining Table'),('Marble Home Interior','Marble Centre Table'),('Marble Home Interior','Marble Side Table'),('Marble Home Interior','Marble Wash Basin'),('Marble Home Interior','Marble Bathroom Counter'),('Marble Home Interior','Marble Window Sill'),('Marble Home Interior','Marble Door Frame'),('Marble Home Interior','Marble Window Frame'),('Marble Home Interior','Marble Skirting'),('Marble Home Interior','Marble Border'),('Marble Home Interior','Marble Inlay Work'),('Marble Home Interior','Marble Jaali'),('Marble Home Interior','Marble Partition'),('Marble Home Interior','Marble Fireplace'),('Marble Home Interior','Marble Temple'),('Marble Home Interior','Marble Pooja Room'),('Marble Home Interior','Marble Decorative Panel'),('Marble Home Interior','Marble Wall Panel'),('Marble Home Interior','Marble Table Top'),('Marble Home Interior','Marble Furniture'),('Marble Home Interior','Marble Home Decor'),('Marble Home Interior','Custom Marble Interior Work'),('Marble Home Interior','Other Marble Interior'),
  ('Granite Home Interior','Granite Kitchen Countertop'),('Granite Home Interior','Granite Kitchen Platform'),('Granite Home Interior','Granite Island Top'),('Granite Home Interior','Granite Bathroom Counter'),('Granite Home Interior','Granite Staircase'),('Granite Home Interior','Granite Steps'),('Granite Home Interior','Granite Window Sill'),('Granite Home Interior','Granite Door Frame'),('Granite Home Interior','Granite Window Frame'),('Granite Home Interior','Granite Skirting'),('Granite Home Interior','Granite Wall Cladding'),('Granite Home Interior','Granite Flooring'),('Granite Home Interior','Granite Table Top'),('Granite Home Interior','Granite Dining Table'),('Granite Home Interior','Granite Centre Table'),('Granite Home Interior','Granite Pooja Platform'),('Granite Home Interior','Granite Temple Work'),('Granite Home Interior','Granite Custom Work'),('Granite Home Interior','Other Granite Interior'),
  ('Marble & Granite Custom Work','Cutting'),('Marble & Granite Custom Work','Edge Profiling'),('Marble & Granite Custom Work','Edge Polishing'),('Marble & Granite Custom Work','Bullnose Edge'),('Marble & Granite Custom Work','Chamfer Edge'),('Marble & Granite Custom Work','Bevel Edge'),('Marble & Granite Custom Work','Waterjet Cutting'),('Marble & Granite Custom Work','CNC Cutting'),('Marble & Granite Custom Work','CNC Engraving'),('Marble & Granite Custom Work','Marble Inlay'),('Marble & Granite Custom Work','Granite Cutting'),('Marble & Granite Custom Work','Slab Cutting'),('Marble & Granite Custom Work','Sink Cutout'),('Marble & Granite Custom Work','Hob Cutout'),('Marble & Granite Custom Work','Basin Cutout'),('Marble & Granite Custom Work','Stair Cutting'),('Marble & Granite Custom Work','Custom Shape Cutting'),('Marble & Granite Custom Work','Polishing'),('Marble & Granite Custom Work','Re-Polishing'),('Marble & Granite Custom Work','Installation'),('Marble & Granite Custom Work','Other Custom Work'),
  ('Bathroom Fittings','Basin Mixer'),('Bathroom Fittings','Pillar Tap'),('Bathroom Fittings','Wall Mixer'),('Bathroom Fittings','Shower Mixer'),('Bathroom Fittings','Concealed Mixer'),('Bathroom Fittings','Diverter'),('Bathroom Fittings','Rain Shower'),('Bathroom Fittings','Hand Shower'),('Bathroom Fittings','Shower Set'),('Bathroom Fittings','Health Faucet'),('Bathroom Fittings','Angle Cock'),('Bathroom Fittings','Bib Cock'),('Bathroom Fittings','Stop Cock'),('Bathroom Fittings','Flush Valve'),('Bathroom Fittings','Sensor Tap'),('Bathroom Fittings','Automatic Tap'),('Bathroom Fittings','Floor Mounted Tap'),('Bathroom Fittings','Bathtub Fittings'),('Bathroom Fittings','Other Bathroom Fittings'),
  ('Bathroom Accessories','Towel Rod'),('Bathroom Accessories','Towel Ring'),('Bathroom Accessories','Towel Rack'),('Bathroom Accessories','Soap Dish'),('Bathroom Accessories','Soap Dispenser'),('Bathroom Accessories','Toothbrush Holder'),('Bathroom Accessories','Toilet Paper Holder'),('Bathroom Accessories','Robe Hook'),('Bathroom Accessories','Bathroom Shelf'),('Bathroom Accessories','Corner Shelf'),('Bathroom Accessories','Glass Shelf'),('Bathroom Accessories','Bathroom Mirror'),('Bathroom Accessories','LED Mirror'),('Bathroom Accessories','Bathroom Cabinet'),('Bathroom Accessories','Other Accessories'),
  ('Bathtub & Shower','Freestanding Bathtub'),('Bathtub & Shower','Corner Bathtub'),('Bathtub & Shower','Acrylic Bathtub'),('Bathtub & Shower','Whirlpool Bathtub'),('Bathtub & Shower','Shower Enclosure'),('Bathtub & Shower','Shower Cubicle'),('Bathtub & Shower','Glass Shower Partition'),('Bathtub & Shower','Shower Panel'),('Bathtub & Shower','Rain Shower'),('Bathtub & Shower','Shower Set'),('Bathtub & Shower','Steam Shower'),('Bathtub & Shower','Other Bathtub & Shower'),
  ('Doors, Windows & Stone Products','Marble Door Frame'),('Doors, Windows & Stone Products','Granite Door Frame'),('Doors, Windows & Stone Products','Marble Window Frame'),('Doors, Windows & Stone Products','Granite Window Frame'),('Doors, Windows & Stone Products','Marble Sill'),('Doors, Windows & Stone Products','Granite Sill'),('Doors, Windows & Stone Products','Stone Door Frame'),('Doors, Windows & Stone Products','Stone Window Frame'),('Doors, Windows & Stone Products','Marble Jali'),('Doors, Windows & Stone Products','Granite Jali'),('Doors, Windows & Stone Products','Decorative Stone Panel'),('Doors, Windows & Stone Products','Natural Stone'),('Doors, Windows & Stone Products','Sandstone'),('Doors, Windows & Stone Products','Limestone'),('Doors, Windows & Stone Products','Slate Stone'),('Doors, Windows & Stone Products','Other Stone Products'),
  ('Mosaic & Decorative Products','Marble Mosaic'),('Mosaic & Decorative Products','Glass Mosaic'),('Mosaic & Decorative Products','Stone Mosaic'),('Mosaic & Decorative Products','Ceramic Mosaic'),('Mosaic & Decorative Products','Metal Mosaic'),('Mosaic & Decorative Products','Marble Inlay'),('Mosaic & Decorative Products','Decorative Border'),('Mosaic & Decorative Products','Marble Border'),('Mosaic & Decorative Products','Tile Border'),('Mosaic & Decorative Products','Designer Panel'),('Mosaic & Decorative Products','3D Wall Panel'),('Mosaic & Decorative Products','Decorative Stone Panel'),('Mosaic & Decorative Products','Other Decorative Products'),
  ('Tile Accessories & Installation Material','Tile Adhesive'),('Tile Accessories & Installation Material','Tile Grout'),('Tile Accessories & Installation Material','Epoxy Grout'),('Tile Accessories & Installation Material','Tile Spacer'),('Tile Accessories & Installation Material','Tile Leveling System'),('Tile Accessories & Installation Material','Tile Cleaner'),('Tile Accessories & Installation Material','Tile Sealer'),('Tile Accessories & Installation Material','Waterproofing Material'),('Tile Accessories & Installation Material','Tile Trim'),('Tile Accessories & Installation Material','Aluminium Trim'),('Tile Accessories & Installation Material','PVC Trim'),('Tile Accessories & Installation Material','Corner Profile'),('Tile Accessories & Installation Material','Tile Cutting Disc'),('Tile Accessories & Installation Material','Other Tile Accessories'),
  ('Plumbing & Bathroom Installation Products','PVC Pipe'),('Plumbing & Bathroom Installation Products','CPVC Pipe'),('Plumbing & Bathroom Installation Products','UPVC Pipe'),('Plumbing & Bathroom Installation Products','Waste Pipe'),('Plumbing & Bathroom Installation Products','Flexible Pipe'),('Plumbing & Bathroom Installation Products','Connection Pipe'),('Plumbing & Bathroom Installation Products','Flush Pipe'),('Plumbing & Bathroom Installation Products','Bottle Trap'),('Plumbing & Bathroom Installation Products','Waste Coupling'),('Plumbing & Bathroom Installation Products','Floor Trap'),('Plumbing & Bathroom Installation Products','Drain'),('Plumbing & Bathroom Installation Products','Grating'),('Plumbing & Bathroom Installation Products','Valve'),('Plumbing & Bathroom Installation Products','Other Plumbing Products'),
  ('Marble / Granite Chemicals & Maintenance','Marble Polish'),('Marble / Granite Chemicals & Maintenance','Granite Polish'),('Marble / Granite Chemicals & Maintenance','Stone Sealer'),('Marble / Granite Chemicals & Maintenance','Marble Cleaner'),('Marble / Granite Chemicals & Maintenance','Granite Cleaner'),('Marble / Granite Chemicals & Maintenance','Stain Remover'),('Marble / Granite Chemicals & Maintenance','Adhesive'),('Marble / Granite Chemicals & Maintenance','Epoxy'),('Marble / Granite Chemicals & Maintenance','Resin'),('Marble / Granite Chemicals & Maintenance','Hardener'),('Marble / Granite Chemicals & Maintenance','Stone Treatment'),('Marble / Granite Chemicals & Maintenance','Waterproofing Chemical'),('Marble / Granite Chemicals & Maintenance','Other Maintenance Products'),
  ('Hardware & Installation Accessories','Sink Clips'),('Hardware & Installation Accessories','Basin Brackets'),('Hardware & Installation Accessories','Vanity Brackets'),('Hardware & Installation Accessories','Mirror Clips'),('Hardware & Installation Accessories','Mirror Brackets'),('Hardware & Installation Accessories','Shelf Brackets'),('Hardware & Installation Accessories','Tile Spacers'),('Hardware & Installation Accessories','Tile Clips'),('Hardware & Installation Accessories','Screws'),('Hardware & Installation Accessories','Anchors'),('Hardware & Installation Accessories','Mounting Kits'),('Hardware & Installation Accessories','Installation Kits'),('Hardware & Installation Accessories','Other Hardware')
)
INSERT INTO subcategories (category_id, name)
SELECT c.id, catalog.subcategory FROM catalog JOIN categories c ON c.name = catalog.category
ON CONFLICT (category_id, name) DO NOTHING;

INSERT INTO units (name, type) VALUES
  ('Set','quantity'),('Job','quantity'),('Running Ft','area'),('Meter','area'),('Bag','quantity'),('Kg','quantity'),('Litre','quantity'),('Custom Order','quantity')
ON CONFLICT (name) DO NOTHING;
